spring:
  config.activate.on-profile: mariadb
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/data
    username: root
    password: example
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect

app.repository: mariadb